services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8097:8096"
      - "8921:8920"  #optional
      - "7359:7359/udp"  #optional
      - "1900:1900/udp"  #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
    volumes:
      - ./config:/config
      - ./tvseries:/data/tvshows
      - ./movies:/data/movies
      - ./music:/data/music
      - /mnt:/data/local


